name: Testing API
on: [push, pull_request]
permissions:
  id-token: write
  contents: read
jobs:
  testing-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-session-name: aws_testing_session
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Creating and activating virtualenv
        run: |
          pip3 install virtualenv
          
      - name: Activate venv   
        run: |
          virtualenv venv 
          source venv/bin/activate
      - name: Installing dependencies
        run: |
          pip install 'dvc[s3]'
          pip install -r requirements_test.txt
      - name : Test API
        run: |
          pip3 install pyOpenSSL
          pip3 install httpx
          dvc pull model/model.pkl -r model-tracker
          pytest test.py
